### ISSUE TITLE
convert to async

### ISSUE THREAD

**Issue by marksie1988** [totaldebug/pyarr#67]
Convert the project to allow asynchronous tasks

**Comment by Archmonger** [comment]
Was looking at your branch for this. What's the reasoning behind a new client construct?

Converting to async should be fairly simple since we're not using any DBs for this repo.

**Comment by marksie1988** [comment]
Hey, 

I'm using it as a way to learn more about async as it's not something I've worked with yet. 

The new client I'm hoping will make it work more efficiently but still quite early on, I have more code that I haven't committed yet which changes a few things from the current commit.

**Comment by Archmonger** [comment]
Since PyArr is fundamentally just a wrapper for requests, I don't think there's any need for a client construct. May just make the code more difficult to read. Just typing `async` in front of every function def would be the easiest way to obtain full async.

If you've ever using threading, async is a very similar concept.

**Comment by marksie1988** [comment]
Yea so my plan is to replace requests with aiohttp. 

I maybe miss understanding something but in order for the async to work correctly doesn't the client connection need creating first and then all functions running through the same connection? 

I believe the current way would create a new connection for each request.

**Comment by Archmonger** [comment]
An alternative is to create a client on each request, rather than a single pool that all connections funnel through. Would directly mimic what we're doing now, not require as much refactoring, and support infinitely many concurrent connections.

```python
async with aiohttp.ClientSession(headers=headers) as session:
    pass
````

**Comment by Archmonger** [comment]
If this ticket stays open till the end of the year, I'll take a look at this. Perhaps we can call it our v3.0 milestone.

**Comment by Archmonger** [comment]
@marksie1988 If we convert to async, are we going to abandon sync methods?

There is no way to be both sync/async without code duplication that I'm aware of.

Also, I can put this build together in less than a day if we agree what path to take.

_Side note: I've become aware [someone has already forked Pyarr v2.x to be async.](https://github.com/tkdrob/aiopyarr)_

**Comment by marksie1988** [comment]
After thinking about this one I was going to create a fork called aiopyarr, however as that has been done I'm not sure if it makes sense to create an async version when one already exists. 

I would still be happy to do it if you felt it a worthwhile task but I'm not sure atm...

**Comment by Archmonger** [comment]
It looks like aiopyarr has changed a few things about our API, so it's not exactly a drop-in replacement. The two big tings are:

1. API configuration is done through objects
2. All API endpoints return Python objects rather than dictionaries

If we had decided to migrate this current repo to be fully async, I intended to make the transition as simple as possible.

By that I mean, the only thing I'd expect users to do is to type `await` in front of their API calls and change nothing else.

If they intend to use the async functions as sync, then things would get visually ugly.

Something we could potentially discuss with the developer is if he'd be willing to have the aiopyarr repo exist within the `totaldebug` organization, that way it can become an "official async pyarr" implementation.

**Comment by marksie1988** [comment]
I did consider seeing if the aiopyarrr creator would join it up so that we can go in as one team. Saves us both having to find new endpoints and changes etc. 

However I didn't think about just adding a async module to this project, that might not be a bad shout. That way we cover both with one package...

**Comment by acortelyou** [comment]
+1 for responses as `TypedDict` and constructors with keyworded arguments (which themselves can be stored in a dict and unpacked if desired).

**Comment by marksie1988** [comment]
I agree I would like to keep the `TypedDict` it has different use cases and like you say would be easier to maintain, last thing we want is to need to do urgent changes because the Servarr team aren't always the best at documenting changes to the APIs (at least not that ive seen) 

I like the idea of `pyarr.async`, `pyarr.sync` and common / utils etc. this would hopefully remove unnecessary duplication, however not something I have done before so question how do you achieve using a common library for sync and async? if there are any Django examples it would be good for me to take a look.

**Comment by Archmonger** [comment]
In terms of writing out API endpoints _(ex. `upd_book(args, kwargs`)_, that code specifically would need to be duplicated. One being in an async fashion and the other being sync.

There are ways to convert async code to be synchronous (and vice-versa), but none of them are performant. If we wanted to avoid code duplication at the cost of performance, the best route would be to write everything async and use [asgiref.async_to_sync](https://github.com/django/asgiref/blob/4fa1c540c33552dbf109a6fa65475561bab2adc8/asgiref/sync.py#L18) or [asyncio.run](https://docs.python.org/3/library/asyncio-task.html#asyncio.run).

All the important Django examples are still under development and haven't been released yet.

**Comment by marksie1988** [comment]
Closing this for the time, not sure if this is needed for the library at the moment. may revisit in the future.
